config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  mount ActionCable.server => '/cable'

  devise_for :users, controllers: {registrations: :registrations}

  resources :rooms, only: [:index, :show, :new, :create]

  root to: 'pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates_presence_of :user, :room

  validates :body, presence: true, length: {minimum: 2, maximum: 1000}

  after_create_commit { MessageBroadcastJob.perform_later(self) }

  def timestamp
    created_at.strftime('%H:%M:%S %d %B %Y')
  end
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user

  has_many :messages, dependent: :destroy

  validates :title, presence: true, length: {maximum: 100}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :rooms, dependent: :destroy
  has_many :messages, dependent: :destroy

  validates :username, presence: true, length: {maximum: 50}, uniqueness: {case_sensitive: false}
  validates :about_me, length: {maximum: 500}

  def online?
    Redis.new.get("user_#{self.id}_online").present?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

  def permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :about_me, :show_email])
  end

  def after_sign_in_path_for(_resource)
    rooms_path
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!

  def home
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  protected

  def after_update_path_for(_resource)
    rooms_path
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    @rooms = Room.all
  end

  def show
    @room = Room.includes(messages: [:user]).find_by(id: params[:id])
    @message = Message.new
  end

  def new
    @room = Room.new
  end

  def create
    @room = current_user.rooms.build(room_params)

    if @room.save
      flash[:success] = 'Chat room added!'
      redirect_to rooms_path
    else
      render 'new'
    end
  end

  private

  def room_params
    params.require(:room).permit(:title, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, opts = {})
    opts[:alt] = user.username

    image_tag("https://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(user.email)}?s=#{opts.delete(:size) { 100 }}",
              opts)
  end

  def bootstrap_class_for(flash_type)
    types = {success: 'alert-success', error: 'alert-danger', alert: 'alert-warning', notice: 'alert-info'}
    types.stringify_keys[flash_type.to_s] || flash_type.to_s
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
  def markdown_to_html(text)
    Kramdown::Document.new(text, input: 'GFM').to_html
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lyria</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
    <link rel="icon" type="image/png" href="/favicon-32x32.png" sizes="32x32">
    <link rel="icon" type="image/png" href="/favicon-16x16.png" sizes="16x16">
    <link rel="manifest" href="/manifest.json">
    <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
    <meta name="theme-color" content="#ffffff">
  </head>

  <body>
    <div class="wrap">
      <%= render partial: 'shared/navbar' %>

      <% flash.each do |message_type, message| %>
        <div class="alert <%= bootstrap_class_for(message_type) %> text-center">
          <a href="#" class="close" data-dismiss="alert">&times;</a>
          <%= message %>
        </div>
      <% end %>

      <%= yield %>
    </div>

    <%= render partial: 'shared/footer' %>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="media">
  <div class="user-avatar media-left media-top">
    <%= gravatar_for message.user %>
  </div>

  <div class="media-body">
    <p class="media-heading">
      <%= message.user.username %>
      <br>

      <span class="small text-muted">at <%= message.timestamp %> says:</span>
    </p>

    <p><%= sanitize markdown_to_html(message.body) %></p>
  </div>
</div>

app/views/pages/home.html.erb
<!-- Header Carousel -->
<header id="myCarousel" class="carousel slide">
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
  </ol>

  <div class="carousel-inner">
    <div class="item active">
      <div class="fill slide-1"></div>

      <div class="carousel-caption">
        <h2>Connect people all over the Globe</h2>
      </div>
    </div>

    <div class="item">
      <div class="fill slide-2"></div>

      <div class="carousel-caption">
        <h2>Everywhere you wish</h2>
      </div>
    </div>

    <div class="item">
      <div class="fill slide-3"></div>

      <div class="carousel-caption">
        <h2>It's easy</h2>
      </div>
    </div>
  </div>

  <a class="left carousel-control" href="#myCarousel" data-slide="prev">
    <span class="icon-prev"></span>
  </a>

  <a class="right carousel-control" href="#myCarousel" data-slide="next">
    <span class="icon-next"></span>
  </a>
</header>

<!-- Page Content -->
<div class="container">
  <div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <div class="page-header text-center">
        <h1>Welcome to <strong>Lyria</strong></h1>
        <p class="lead">A place for <em>unlimited</em> chatting</p>
      </div>
    </div>

    <div class="clearfix"></div>

    <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
      <div class="panel panel-info">
        <div class="panel-heading">
          <h4>
            <i class="glyphicon glyphicon-ok brand-success"></i>
            <span>Join for free</span>
          </h4>
        </div>

        <div class="panel-body">
          <p>
            It's totally free for everyone. All you need is just to confirm your registration through your email.
            And that's it.
          </p>

          <%= link_to 'Register now', new_user_registration_path, class: 'btn btn-default' %>
        </div>
      </div>
    </div>

    <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
      <div class="panel panel-info">
        <div class="panel-heading">
          <h4>
            <i class="glyphicon glyphicon-bullhorn brand-gray"></i>
            <span>Real time conversations</span>
          </h4>
        </div>

        <div class="panel-body">
          <p>
            Create unlimited real-time chat rooms or join any existing one. All your chat history will be
            saved and accessible anytime and everywhere.
          </p>
        </div>
      </div>
    </div>

    <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
      <div class="panel panel-info">
        <div class="panel-heading">
          <h4>
            <i class="glyphicon glyphicon-star brand-warning"></i>
            <span>Powerful and secure</span>
          </h4>
        </div>

        <div class="panel-body">
          <p>
            Our Application is built using the most modern and secure web framework ever -
            <a href="http://rubyonrails.org/" target="_blank">Ruby on Rails</a>. Just enjoy the Application and be
            sure - your data is protected well.
          </p>
        </div>
      </div>
    </div>
  </div>

  <!-- Features Section -->
  <div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <h2 class="page-header">Mobile version is available</h2>
    </div>

    <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
      <div class="panel panel-success">
        <div class="panel-heading">
          <h4>
            <i class="glyphicon glyphicon-phone brand-primary"></i>
            <span>Keep chatting at home, in park, everywhere</span>
          </h4>
        </div>

        <div class="panel-body">
          <p>
            We also have a responsive version of our Application, optimized for mobile phones and tablets. Take all
            your chat rooms with you - in your mobile device.
          </p>
        </div>
      </div>
    </div>

    <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
      <%= image_tag 'promo_mobile.jpg', class: 'img-responsive', alt: 'Mobile version' %>
    </div>
  </div>

  <br>

  <!-- Call to Action Section -->
  <div class="well">
    <div class="row">
      <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12">
        <p class="text-center">
          Are you ready to start chatting?
          <br>
          It will take a couple of minutes to join in.</p>
      </div>

      <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
        <%= link_to new_user_registration_path, class: 'btn btn-lg btn-default btn-block' do %>
          <i class="glyphicon glyphicon-link" aria-hidden="true"></i>
          <span>Sign up now</span>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/rooms/_room.html.erb
<%= link_to room_path(room), class: 'list-group-item' do %>
  <h4 class="list-group-item-heading">
    <%= room.title %>

    <span class="badge"><%= room.messages.count %></span>
  </h4>

  <p class="list-group-item-text text-muted"><%= room.description %></p>
<% end %>

app/views/rooms/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-6 col-lg-offset-3 col-md-6 col-md-offset-3 col-sm-6 col-sm-offset-3 col-xs-12">
      <div class="page-header text-center">
        <h1>Chat rooms</h1>
      </div>

      <p class="text-right">
        <%= link_to new_room_path, class: 'btn btn-primary' do %>
          <i class="glyphicon glyphicon-plus" aria-hidden="true"></i>
          <span>New chat room</span>
        <% end %>
      </p>

      <div class="list-group">
        <%= render @rooms %>
      </div>
    </div>
  </div>
</div>

app/views/rooms/new.html.erb
<div class="container m-t-lg">
  <div class="row">
    <div class="col-lg-6 col-lg-offset-3 col-md-6 col-md-offset-3 col-sm-6 col-sm-offset-3 col-xs-12">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title text-center">New chat room</h3>
        </div>

        <div class="panel-body">
          <%= form_for @room do |f| %>
            <%= render 'shared/error_messages', object: @room %>

            <div class="form-group">
              <label for="title">Title:</label>

              <div class="input-group">
                <span class="input-group-addon">
                  <i class="glyphicon glyphicon-tag" aria-hidden="true"></i>
                </span>

                <%= f.text_field :title, autofocus: true, class: 'form-control' %>
              </div>
            </div>

            <div class="form-group">
              <label for="description">Description:</label>

              <div class="input-group">
                <span class="input-group-addon">
                  <i class="glyphicon glyphicon-tag" aria-hidden="true"></i>
                </span>

                <%= f.text_field :description, class: 'form-control' %>
              </div>
            </div>

            <%= f.submit 'Create', class: 'btn btn-default' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/rooms/show.html.erb
<div class="container m-t-lg m-b-md">
  <div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <div class="panel panel-primary">
        <div class="panel-heading text-center">
          <h3 class="panel-title">
            <a class="show-users-list pull-right" role="button" data-toggle="collapse" href="#collapseUsersList"
               aria-expanded="false" aria-controls="collapseUsersList" title="Show messaged users">
              <i class="glyphicon glyphicon-menu-down" aria-hidden="true"></i>
            </a>

            <%= @room.title %>
          </h3>

          <span class="small">
            <%= @room.description %>
          </span>

          <div class="collapse users-list" id="collapseUsersList">
            <ul class="list-inline">
              <% if @room.messages.count == 0 %>
                <li>
                  <em>No users messaged yet.</em>
                </li>
              <% else %>
                <% @room.messages.map(&:user).uniq.each do |user| %>
                  <li>
                    <%= content_tag :a, role: 'button', tabindex: 0, title: "About #{user.username}", class: 'card-link',
                                    data: {toggle: 'popover', trigger: 'hover focus', placement: 'bottom', html: true,
                                           content: "#{render partial: 'shared/user_card', locals: {user: user}}"} do %>
                      <i class="glyphicon glyphicon-user user-<%= user.id %> online_status <%= 'online' if user.online? %>"
                         aria-hidden="true"></i>
                      <%= user.username %>
                    <% end %>
                  </li>
                <% end %>
              <% end %>
            </ul>
          </div>
        </div>

        <div class="panel-body">
          <div id="messages" data-room-id="<%= @room.id %>">
            <% if @room.messages.count > 0 %>
              <%= render @room.messages %>
            <% else %>
              <p class="text-muted text-center">
                <em>No messages were sent yet.</em>
              </p>
            <% end %>
          </div>
        </div>

        <div class="panel-footer text-center">
          We support <a href="http://daringfireball.net/projects/markdown" target="_blank">Markdown</a>:
          use <code>**Bold**</code> for <strong>Bold</strong> styling, <code>*Italic*</code> for <em>Italic</em>
          styling or <code>`monospace`</code> for <code>monospace</code> styling
        </div>
      </div>

      <%= form_for @message, url: '#' do |f| %>
        <div class="form-group">
          <div class="input-group">
            <span class="input-group-addon">
              <i class="glyphicon glyphicon-comment" aria-hidden="true"></i>
            </span>

            <%= f.text_area :body, class: 'form-control vertical', placeholder: 'Your message...', minlength: '2',
                            maxlength: '1000', required: true %>
          </div>

          <small class="text-muted">From 2 to 1000 characters</small>
        </div>

        <%= button_tag type: 'submit', class: 'btn btn-primary' do %>
          <i class="glyphicon glyphicon-send" aria-hidden="true"></i>
          <span class="m-l-xs">Send message</span>
        <% end %>

        <span class="text-muted hidden-xs">
          or press <kbd><kbd>Shift</kbd> + <kbd>Enter</kbd></kbd>
        </span>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div class="error_explanation m-b-md">
    <div class="alert alert-danger">
      <h4>
        <i class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></i>
        The form contains <%= pluralize(object.errors.count, 'error') %>.
      </h4>

      <ul>
        <% object.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer-basic-centered">
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <p class="footer-company-name">
          Lyria - <%= Date.current.year %>
        </p>
      </div>
    </div>

    <div class="row">
      <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <p class="footer-text">
          Thank you for helping us help you help us all
          <i class="glyphicon glyphicon-heart" aria-hidden="true"></i>
        </p>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
              data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <% if user_signed_in? %>
        <%= link_to rooms_path, class: 'navbar-brand' do %>
          <%= image_tag 'logo.png', alt: 'Lyria' %>
        <% end %>
      <% else %>
        <%= link_to root_path, class: 'navbar-brand' do %>
          <%= image_tag 'logo.png', alt: 'Lyria' %>
        <% end %>
      <% end %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li>
            <%= link_to rooms_path do %>
              <i class="glyphicon glyphicon-th-list" aria-hidden="true"></i>
              <span>Chat rooms</span>
            <% end %>
          </li>
          <li>
            <%= link_to edit_user_registration_path do %>
              <i class="glyphicon glyphicon-edit" aria-hidden="true"></i>
              <span><%= current_user.username %></span>
            <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
              <i class="glyphicon glyphicon-log-out" aria-hidden="true"></i>
              <span>Logout</span>
            <% end %>
          </li>
        <% else %>
          <li>
            <%= link_to new_user_session_path do %>
              <i class="glyphicon glyphicon-log-in" aria-hidden="true"></i>
              <span>Login</span>
            <% end %>
          </li>
          <li>
            <%= link_to new_user_registration_path do %>
              <i class="glyphicon glyphicon-link" aria-hidden="true"></i>
              <span>Sign up</span>
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_user_card.html.erb
<div class="card hover-card">
  <div class="card-header"></div>

  <div class="avatar">
    <%= gravatar_for user %>
  </div>

  <div class="info">
    <div class="title">
      <%= user.username %>
    </div>

    <% if user.show_email %>
      <div class="desc"><%= mail_to user.email %></div>
    <% end %>

    <% if user.about_me.present? %>
      <div class="desc"><%= user.about_me %></div>
    <% end %>

    <div class="desc">Signed up: <%= user.confirmed_at.strftime('%d %B %Y') %></div>
  </div>
</div>